// <auto-generated />
using MetalBroxstarChaos.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetalBroxstarChaos.Datos.Migrations
{
    [DbContext(typeof(BroxstarContext))]
    partial class BroxstarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MetalBroxstarChaos.Modelos.Clase", b =>
                {
                    b.Property<int>("idClase")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombreClase");

                    b.HasKey("idClase");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            idClase = 1,
                            nombreClase = "Guerrero"
                        },
                        new
                        {
                            idClase = 2,
                            nombreClase = "Mago"
                        },
                        new
                        {
                            idClase = 3,
                            nombreClase = "Paladín"
                        },
                        new
                        {
                            idClase = 4,
                            nombreClase = "Pícaro"
                        });
                });

            modelBuilder.Entity("MetalBroxstarChaos.Modelos.Habilidad", b =>
                {
                    b.Property<int>("idHabilidad")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idPersonaje");

                    b.Property<string>("nombreHabilidad");

                    b.Property<int>("poder");

                    b.HasKey("idHabilidad");

                    b.HasIndex("idPersonaje");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("MetalBroxstarChaos.Modelos.Personaje", b =>
                {
                    b.Property<int>("idPersonaje")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idClase");

                    b.Property<int>("nivelPersonaje");

                    b.Property<string>("nombrePersonaje");

                    b.HasKey("idPersonaje");

                    b.HasIndex("idClase");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("MetalBroxstarChaos.Modelos.Habilidad", b =>
                {
                    b.HasOne("MetalBroxstarChaos.Modelos.Personaje")
                        .WithMany("Habilidades")
                        .HasForeignKey("idPersonaje")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MetalBroxstarChaos.Modelos.Personaje", b =>
                {
                    b.HasOne("MetalBroxstarChaos.Modelos.Clase", "clase")
                        .WithMany()
                        .HasForeignKey("idClase")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
